In [1]:
from google.colab import files

uploaded = files.upload()


ModuleNotFoundError: No module named 'google.colab'

In [1]:
%matplotlib inline

import numpy as np
import pandas as pd
import matplotlib.pyplot

df = pd.read_csv('mlb1_v2.csv')

df.head()

score  BA  H  RBI  BB  k  SB  holds  avgR  ER  bb  SO  nHR
0      4  35  9    4   4  5   1      9     4   4   4   5    1
1      3  33  7    2   1  2   1      7     3   1   1   2    0
2      1  32  6    1   5  6   1      6     1   1   5   6    1
3      3  28  4    2   4  5   0      4     3   3   4   5    0
4      0  32  7    0   1  1   0      7     0   0   1   1    0

x = df.loc[:,"BA":].values

In [2]:
x = df.loc[:,"H":].values.astype(np.float64)

In [3]:
y = df["score"].values.astype(np.float64)

In [54]:
y

array([4., 3., 1., ..., 0., 2., 3.])

In [102]:
# x = x.reshape(len(x),1)/10

In [26]:
len(x_train) == len(y_train)

True

In [4]:
from sklearn.model_selection import train_test_split


x_train, x_test, y_train, y_test = train_test_split(x, y,
                                                   test_size=0.2,
                                                   random_state=87)

In [5]:
x_train.shape

(7964, 11)

In [6]:
x_test.shape

(1992, 11)

In [7]:
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD

In [8]:
model = Sequential()
model.add(Dense(100, input_dim=11, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(1))

In [9]:
model.compile(loss='mse', optimizer=SGD(lr=0.00001),
              #'adam',
              #SGD(lr=0.087), 
              metrics=['accuracy'])

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 100)               1200      
_________________________________________________________________
dense_1 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 101       
Total params: 11,401
Trainable params: 11,401
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.fit(x_train, y_train, batch_size=200, epochs=100)


Train on 7964 samples
Epoch 1/100
7964/7964 [==============================] - 0s 37us/sample - loss: 0.6024 - accuracy: 0.1219
Epoch 2/100
7964/7964 [==============================] - 0s 25us/sample - loss: 0.5948 - accuracy: 0.1222
Epoch 3/100
7964/7964 [==============================] - 0s 28us/sample - loss: 0.5874 - accuracy: 0.1227
Epoch 4/100
7964/7964 [==============================] - 0s 25us/sample - loss: 0.5803 - accuracy: 0.1233
Epoch 5/100
7964/7964 [==============================] - 0s 29us/sample - loss: 0.5733 - accuracy: 0.1236
Epoch 6/100
7964/7964 [==============================] - 0s 25us/sample - loss: 0.5666 - accuracy: 0.1239
Epoch 7/100
7964/7964 [==============================] - 0s 24us/sample - loss: 0.5600 - accuracy: 0.1241
Epoch 8/100
7964/7964 [==============================] - 0s 27us/sample - loss: 0.5535 - accuracy: 0.1242
Epoch 9/100
7964/7964 [==============================] - 0s 25us/sample - loss: 0.5473 - accuracy: 0.1246
Epoch 10/100
7964/7964 [

7964/7964 [==============================] - 0s 30us/sample - loss: 0.3336 - accuracy: 0.1357
Epoch 78/100
7964/7964 [==============================] - 0s 28us/sample - loss: 0.3320 - accuracy: 0.1357
Epoch 79/100
7964/7964 [==============================] - 0s 29us/sample - loss: 0.3305 - accuracy: 0.1361
Epoch 80/100
7964/7964 [==============================] - 0s 29us/sample - loss: 0.3290 - accuracy: 0.1360
Epoch 81/100
7964/7964 [==============================] - 0s 29us/sample - loss: 0.3275 - accuracy: 0.1361
Epoch 82/100
7964/7964 [==============================] - 0s 24us/sample - loss: 0.3260 - accuracy: 0.1362
Epoch 83/100
7964/7964 [==============================] - 0s 24us/sample - loss: 0.3246 - accuracy: 0.1364
Epoch 84/100
7964/7964 [==============================] - 0s 23us/sample - loss: 0.3232 - accuracy: 0.1366
Epoch 85/100
7964/7964 [==============================] - 0s 23us/sample - loss: 0.3218 - accuracy: 0.1366
Epoch 86/100
7964/7964 [==========================

In [40]:
predict = model.predict_classes(x_test)

n = 2

print('神經網路預測是:', predict[n])

神經網路預測是: [1]


In [23]:
y_train

array([1, 1, 0, ..., 1, 6, 8])

In [43]:
x_train[12].dtype

dtype('int64')

In [42]:
y_train[12]

6

In [111]:
model.predict(x_test)

array([[4.854472],
       [4.854472],
       [4.854472],
       ...,
       [4.854472],
       [4.854472],
       [4.854472]], dtype=float32)